# 服务端口
server:
  port: 8086

# mybatis-plus 默认扫描mapper.xml的目录
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  #配置sql打印日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 生效的环境
spring:
  profiles:
    # dev\prod
    active: dev